### PR TITLE
Faster colors

### LINKED ISSUE #720: --color=always ~10x slower
**Describe the bug you encountered:**

I understand that outputting the escape sequences for colors is more text, but I didn't expect it to be 10x slower. Is this expected behavior?

**Describe what you expected to happen:**

Expected `color=always` to not be 10x slower, although maybe I'm simply misguided.

image

**What version of `fd` are you using?**
`fd 8.2.1` (`fd-8.2.1-1` on the AUR)

**Which operating system / distribution are you on?**

```
Linux 5.10.10-arch1-1 x86_64
```

and `lsb_release` but I don't think it's very helpful :)
```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
Ryzen 3900x (24 threads) but it seemed during the bench mark only ~80% cpu was being used.

### PR DESCRIPTION
**Pull request by tavianator**
This can give a significant performance benefit:

    $ hyperfine ./fd-{before,after}" --color=always -HI -j1 --search-path=../../linux >/dev/null"
    Benchmark #1: ./fd-before --color=always -HI -j1 --search-path=../../linux >/dev/null
      Time (mean ± σ):     802.3 ms ±   4.8 ms    [User: 360.0 ms, System: 531.7 ms]
      Range (min … max):   795.8 ms … 808.9 ms    10 runs
 
    Benchmark #2: ./fd-after --color=always -HI -j1 --search-path=../../linux >/dev/null
      Time (mean ± σ):     263.3 ms ±   3.0 ms    [User: 166.4 ms, System: 190.0 ms]
      Range (min … max):   259.0 ms … 268.0 ms    11 runs
 
    Summary
      './fd-after --color=always -HI -j1 --search-path=../../linux >/dev/null' ran
        3.05 ± 0.04 times faster than './fd-before --color=always -HI -j1 --search-path=../../linux >/dev/null'

Fixes #720.  On the other hand, it does lose the distinct colors for 
symlinks along the path, as you mentioned in
https://github.com/sharkdp/fd/issues/720#issuecomment-778680554.

### CODE REVIEW

File: src/output.rs [hunk 1]
```diff
@@ -51,29 +45,41 @@ fn print_entry_colorized(
...
+    if offset > 0 {
+        let mut parent_str = Cow::from(&path_str[..offset]);
         if let Some(ref separator) = config.path_separator {
-            *path_string.to_mut() = replace_path_separator(&path_string, separator);
+            *parent_str.to_mut() = replace_path_separator(&parent_str, separator);
         }
-        write!(stdout, "{}", style.paint(path_string))?;
 
-        // TODO: can we move this out of the if-statement? Why do we call it that often?
-        if wants_to_quit.load(Ordering::Relaxed) {
```
Comment (tavianator) [inline src/output.rs:71]: I think I have misinterpreted the reason for this code and we need to keep this check

**Comment by tavianator** [comment]
I even have an idea of how to bring the per-component colors back, but it would need changes to `ignore`

File: src/output.rs [hunk 2]
```diff
@@ -53,32 +54,51 @@ fn print_entry_colorized(
...
+
+    if let Some(parent) = path.parent() {
+        offset = parent.to_string_lossy().len();
+        for c in path_str[offset..].chars() {
+            if std::path::is_separator(c) {
+                offset += c.len_utf8();
+            } else {
+                break;
+            }
+        }
```
Comment (sharkdp) [inline src/output.rs:69]: I don't understand how this code could be triggered?

Comment (tavianator) [reply src/output.rs:69]: Say the (user supplied) path is `a/b///c`.  `parent` will be `a/b`.  This loop then advances the length to include `a/b///`.

Comment (sharkdp) [reply src/output.rs:69]: Ah! Thank you.

**Review by sharkdp — APPROVED** [review]
